import { Footer } from "@/components/footer/Footer";
import { Hero } from "@/components/hero/Hero";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Hero />
        {children}
        <Footer />
      </body>
    </html>
  );
}