import { NavBar } from "@/components/navbar/NavBar";
import { Footer } from "@/components/footer/Footer";
import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App", // Replace with appropriate default metadata
  description: "Generated by create next app", // Replace with appropriate default metadata
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="bg-zinc-950 text-zinc-200 selection:bg-zinc-600">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}